### ISSUE TITLE
[BUG] Don't Work Kill Switch

### ISSUE THREAD

**Issue by Nemial** [ProtonVPN/protonvpn-cli-ng#101]
**Describe the bug**
In this update, we restored the program's functionality(thank you for that!), but broke the KillSwitch. When you select it, the program breaks down and displays this

```
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 8, in <module>
    sys.exit(main())
  File "/usr/lib64/python3.8/site-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/lib64/python3.8/site-packages/protonvpn_cli/cli.py", line 143, in cli
    configure_cli()
  File "/usr/lib64/python3.8/site-packages/protonvpn_cli/cli.py", line 340, in configure_cli
    set_killswitch()
  File "/usr/lib64/python3.8/site-packages/protonvpn_cli/cli.py", line 590, in set_killswitch
    if killswitch and int(get_config_value("USER", "split_tunnel")):
  File "/usr/lib64/python3.8/site-packages/protonvpn_cli/utils.py", line 122, in get_config_value
    return config[group][key]
  File "/usr/lib64/python3.8/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'split_tunnel'
```

**Desktop (please complete the following information):**
 - OS: Slackware Current
 - Python Version: 3.8.1
 - ProtonVPN-CLI Version: 2.2.1

**Comment by lgommans** [comment]
Same issue here. As the error hints:

> File "/usr/lib64/python3.8/configparser.py", line 1254, in __getitem__  
> KeyError: 'split_tunnel'

The config value for `split_tunnel` is missing.

You can work around the problem by editing `~/.pvpn-cli/pvpn-cli.cfg` and setting `split_tunnel = 0` in the `[USER]` section.

I've submitted a pull request (as shown in the references above) that fixes the issue, but since defaults are only set upon initialization, you'd have to re-initialize your protonvpn-cli, so it's probably easiest to set the default manually if you have an existing installation.

**Comment by Rafficer** [comment]
So to be precise, this breaks activating the Kill Switch via `protonvpn configure`, not the Kill Switch itself, right?

Please completely fill out the issue template next time and don't remove important parts of it... :/

**Comment by Nemial** [comment]
Yes, that's right. Well, next time I'll fill it out completely

**Comment by lgommans** [comment]
I just tested (with my patch), the kill switch works. When I `pkill openvpn`, internet (or at least, pinging my website) is unavailable until I run `protonvpn-cli d`.
