### ISSUE TITLE
[Enhancement] Create a status json file once connected.

### ISSUE THREAD

**Issue by nsantiago2719** [ProtonVPN/protonvpn-cli-ng#53]
**Is your feature request related to a problem? Please describe.**
Some how yes, I was using i3 blocks for my chooses Linux distro and I want to add some information if I'm connected to VPN or not, this includes country, IP address and connection status but using `protonvpn status` every time is a hassle at the same time it's quite take 2-3 seconds to give the info and it's not on format that I want so it's harder for me to display the status.

**Describe the solution you'd like**
I'm not sure if this is a good solution but creating a file with the information in json format should help, it's easier too to check if I'm connected or not. You just need to check if the file exist or not and if it existed you can extract the data in it also once you got disconnected to the VPN it should be purged automatically. 

**Describe alternatives you've considered**
A my current solution is to run a `curl` command on certain url to get my IP once I detect a process of openvpn but this is something that I want to avoid because every minute I need to run certain commands and `curl` a certain URL.

**Comment by Rafficer** [comment]
I don't see a general use case for adding this feature. Since ProtonVPN-CLI doesn't have a background process, yet, it can't automatically update that file, so to get accurate information, you'd need to call `protonvpn update` periodically anyway.

It would probably be easier and better to write a quick script that parses the output of `protonvpn status` and saves it as a json file somewhere. You can then let this script run every few minutes as a cron job.

**Comment by nsantiago2719** [comment]
Then how about supporting a JSON format for `protonvpn s` command? This will ease the the parsing just in case someone want to use the output of the command.

**Comment by Rafficer** [comment]
This will likely be something in the future when ProtonVPN-CLI gets turned into a daemon, rather than a one-shot program. The communication between programs and the daemon will then likely be json.

However, I don't think it's a great idea to add this now, as it adds a few unclear scenarios, especially with handling error messages, which in some cases don't come from the status function directly.

**Comment by nsantiago2719** [comment]
Ah got it. Anyways it seems I some API Endpoints is available once connected to the VPN, I guess I'll use those for now since they're on JSON format.
