### ISSUE TITLE
[BUG] Killswitch breaks connections to localhost servers

### ISSUE THREAD

**Issue by barrosfelipe** [ProtonVPN/protonvpn-cli-ng#9]
Can't establish connections to localhost servers.

**To Reproduce**
1. Enable the killswitch while connected or connect after enabling it.
2. Serve something on localhost.
3. Try to connect to said localhost server through a client and it will never connect.

**Expected behavior**
As a developer, I expect that the killswitch feature will not affect my ability to connect to localhost servers and step 3 would result in a successful connection.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10
 - Python Version: 3.7.3
 - ProtonVPN-CLI Version: 2.0.0

**Comment by Rafficer** [comment]
I think for long-term there needs to be an option to add custom rules to the killswitch. Only problem I see is how to properly sanitize them to not make it able to run specific commands as root that are just written in a text file. This would then also resolve #7.

Regardless of this, I think localhost should be available by default, so I'll look into adding this for the next release.

**Comment by Rafficer** [comment]
The latest version with that fix has been pushed to pypi, so you can upgrade the package now. Would be great if you could leave some feedback on whether or not it works as you expect now :)

**Comment by barrosfelipe** [comment]
It does allow me to work on localhost again, so thank you.

Two other questions came up while playing with it though: should the killswitch stop traffic even when we purposefully disconnect from the VPN? Right now it doesn't. Should it still work even if the VPN process is killed? What about across restarts? In my opinion, users who desire the killswitch features are probably looking to have all that. At least I surely am. If it isn't your intention to implement those features or there is some technical limitation, I believe it may be the case to document that in the README and perhaps provide instructions on how to solve those problems using systemd or some other method. What do you think?

Again, thank you so much. The overall protonvpn-cli experience improved dramatically.

**Comment by Rafficer** [comment]
Yes, it's expected to only "activate" when the VPN connection closes unexpectedly (killing the OpenVPN process manually simulates that). So normal disconnects via the clients and computer restarts would deactivate the Kill Switch again and allow normal internet usage without ProtonVPN.

The problems I see is if it works as you describe that after you disconnect you can't reconnect again because the normal interface is blocked by the kill switch, so you'd need to deactivate the kill switch anyway to be able to connect again.

Afaik this is how all clients on the other OSs work as well, so I don't really intent to change this. I personally also wouldn't expect a Kill Switch to work differently, for me it's only for unexpected connection drops. But if I'm entirely alone with this we can see how it might be changed.

About documentation, not sure if the README is the correct place for this as it doesn't mention the Kill Switch at all right now. [The print when configuring the Kill Switch already says "unexpectedly" right now](https://github.com/ProtonVPN/protonvpn-cli-ng/blob/f1fa3f9a25be4a0bb17fffab208ac44aa6addc68/protonvpn_cli/cli.py#L543), maybe this can be made more clear. I'll also see if ProtonVPN can clarify this a bit more in the upcoming announcements when they talk about the Kill Switch specifically.

> The overall protonvpn-cli experience improved dramatically.

Really happy to hear that, thank you!
